// 卡片／茶會文字都在這份檔案改。
// 正面：title、subtitle、frontBlocks
// 反面：backTitle、backNote、backBlocks
// blocks：p 段落、h 小標、item 條目、qr、map

export const GOOGLE_FORM_URL = "https://forms.gle/ZMXHPimzk4EWRZzCA";

export const LINKS = {
  form: GOOGLE_FORM_URL,
  instagram: "https://www.instagram.com/ntuagca?igsh=MWo4MjJmMHZ4aXE5dg==",
  lineClass: "https://line.me/ti/g/LmKM9JARp-",
  facebook: "https://www.facebook.com/share/g/1TY3Wbttwj/?mibextid=wwXIfr",
  lineCommunity:
    "https://line.me/ti/g2/4UZXoqSxW0V1Zgq70hzRsq46JlTp2-56Sod4Hw?utm_source=invitation&utm_medium=link_copy&utm_campaign=default",
  courses:
    "https://docs.google.com/document/d/12QNo6Lh4o1GQHdQqadSrOZHXlJu0aNH8P4PA8vRtAXA/edit?usp=drivesdk",
};

export const CARDS = [
  {
    id: 1,
    kicker: "01  /  LETTER",
    title: "至新一代的你",
    subtitle: "歡迎來到國立臺灣藝術大學圖文傳播藝術學系。",
    frontQuote: "To the next of you.",
    frontLabel: "LETTER",
    body: [
      "本系以設計、攝影、印刷、出版四大領域為核心，結合理論與實務，培養兼具數位應用能力與美學素養的人才。而系學會，將陪伴你走過這四年的成長與蛻變。",
      "在浮洲，一起書寫屬於自己的敘事，留下獨一無二的篇章。",
    ],
    frontBlocks: [
      {
        type: "p",
        text: "本系以設計、攝影、印刷、出版四大領域為核心，結合理論與實務，培養兼具數位應用能力與美學素養的人才。而系學會，將陪伴你走過這四年的成長與蛻變。",
      },
      { type: "p", text: "在浮洲，一起書寫屬於自己的敘事，留下獨一無二的篇章。" },
    ],
    backTitle: "系所位置",
    backNote: "校園地圖、系所位置，以及可點擊加入的常用連結 QR。",
    backItems: ["圖文傳播藝術學系｜大觀路一段 59 號", "QR 可點擊加入常用連結"],
    backBlocks: [
      { type: "p", text: "此圖為校園地圖及系所位置參考。下方 QR Code 可點擊加入班群與系上頻道。" },
      { type: "map" },
      { type: "item", title: "地址", text: "220 新北市板橋區大觀路一段 59 號" },
      { type: "item", title: "系所", text: "圖文傳播藝術學系（校本部）" },
      { type: "h", text: "常用連結 QR" },
      { type: "p", text: "班群、圖文社群、系學會 IG、台藝人請進、台藝好課，點擊即可加入。" },
      { type: "qr" },
    ],
  },
  {
    id: 2,
    kicker: "02  /  CAMPUS",
    title: "台藝怎麼到",
    subtitle: "交通指南：火車、公車、汽車、機車與 YouBike。",
    frontQuote: "How to arrive.",
    frontLabel: "TRANSIT",
    body: ["浮洲車站步行約五分鐘即可抵達台藝大。"],
    frontBlocks: [
      { type: "h", text: "火車" },
      {
        type: "p",
        text: "搭乘臺鐵區間車至「浮洲車站」，出站後步行約 5 分鐘即可抵達國立臺灣藝術大學。若從「板橋車站」出發，搭乘區間車約 3 分鐘即可抵達「浮洲車站」。",
      },
      { type: "item", title: "提醒", text: "區間快車不停靠浮洲車站，搭乘前請留意列車停靠資訊。" },
      { type: "h", text: "公車" },
      { type: "item", title: "從板橋車站出發", text: "步行約 8 分鐘至「萬坪公園」站，可搭乘 264、701、702、793 至台藝大；步行約 4 分鐘至「板橋公車站」，可搭乘 702、F502 至台藝大。" },
      { type: "item", title: "從捷運府中站出發", text: "步行約 6 分鐘至「北門街」站，可搭乘 264、701、702、793 至台藝大。" },
      { type: "h", text: "汽車" },
      { type: "p", text: "校內設有三處汽車停車區：每學期停車費 NT$1,000，每學年 NT$2,000。" },
      { type: "item", title: "A 區", text: "工藝系側門旁" },
      { type: "item", title: "C 區", text: "位於後門" },
      { type: "item", title: "D 區", text: "位於後門，目前因整修暫停開放，須繞道進出。" },
      { type: "h", text: "機車" },
      { type: "p", text: "每學期停車費 NT$400。須至行政大樓申請「機車停車證」。未申請停車證停放校內，將依規定開罰。申請後可停放於 A 區及北側機車停車場。" },
      { type: "h", text: "腳踏車／YouBike" },
      { type: "p", text: "校內設有三處免費腳踏車停放區：雕塑學系後方、圖書館後方、女二舍與古蹟藝術修護學系塑造教室之間。校門口左側（鄰近郵局）設有 YouBike 租借站，可於此借車、還車。" },
    ],
    backTitle: "你好 我吃一口",
    backNote: "美食指南：後街、僑中二街、大觀路與湳雅夜市。",
    backItems: ["後街", "僑中二街", "大觀路", "湳雅夜市"],
    backBlocks: [
      { type: "h", text: "後街" },
      { type: "item", title: "書店咖啡", text: "結合二手書店與咖啡廳，販售輕食、簡餐、健康餐盒及咖啡。店內一、二樓皆有座位，冬天推薦焦糖牛奶，還有可愛店貓陪伴。" },
      { type: "item", title: "蔥抓餅", text: "全素小店，可選擇加蛋、起司，也販售炒麵、炒飯，還有親人的虎斑店貓。" },
      { type: "item", title: "溫州大餛飩", text: "提供餛飩、麵類及各式湯品，是日常用餐的好選擇。" },
      { type: "item", title: "巷弄小廚", text: "每日更換菜單，提供家常料理、下午茶與輕食。加入 LINE 後可提前查看每日菜單並預訂餐點。" },
      { type: "item", title: "JAG 浮洲", text: "露營風格小店，販售瓜仔肉飯、輕食、甜點與飲品，適合聊天放鬆。" },
      { type: "item", title: "雲味香", text: "提供雲泰料理與飲品，老闆娘親切，熟客還有機會一起唱歌。" },
      { type: "item", title: "意饗麵食", text: "販售義大利麵、丼飯等餐點，也提供線上點餐服務。" },
      { type: "h", text: "僑中二街" },
      { type: "item", title: "泰夯串燒", text: "泰式串燒居酒屋，適合聚餐聊天，店內設有低消限制。" },
      { type: "item", title: "出乎義料", text: "提供義大利麵、燉飯與焗烤，可自由搭配配料。辣度較高，怕辣者請注意。" },
      { type: "item", title: "滷廣眾滷味", text: "人氣加熱滷味店，品項豐富，價格親民，用餐時段可能需要排隊。" },
      { type: "item", title: "天津烤肉飯（美味大便當）", text: "份量十足的便當選擇，適合想快速解決一餐的同學。" },
      { type: "item", title: "安佳牛排館", text: "平價牛排選擇，適合想吃肉類料理時前往。" },
      { type: "item", title: "僑中香雞排", text: "在地人氣炸物店，適合作為晚餐或宵夜點心。" },
      { type: "item", title: "華中水餃館", text: "提供水餃、麵食等中式餐點，適合日常用餐。" },
      { type: "h", text: "大觀路" },
      { type: "item", title: "浮島日常", text: "提供甜點、飲品與簡餐，店內有可愛店貓陪伴，是下午休息的好地方。" },
      { type: "item", title: "CIRCLE 24H 無人拉麵店", text: "24 小時營業，除了韓國拉麵，也提供披薩與飲料，是夜晚聚餐、消夜的好選擇。" },
      { type: "item", title: "裏通路", text: "復古風深夜酒吧，餐點也深受好評，推薦炒麵與炸豆腐，還有親人的店狗「焦糖」。未滿十八歲禁止飲酒；喝酒不開車，開車不喝酒。" },
      { type: "h", text: "湳雅夜市" },
      { type: "p", text: "距離學校較近的大型夜市，從各式小吃、甜點到日用品都能找到。附近也有勝立生活百貨，住宿生可以順便購買生活用品。" },
      { type: "item", title: "大花香腸", text: "人氣香腸攤，香氣十足、口感多汁，是湳雅夜市推薦必吃。" },
      { type: "item", title: "千尋味", text: "販售酸辣粉等特色小吃，酸辣開胃。" },
      { type: "item", title: "奶 Q 地瓜球", text: "外酥內 Q，適合作為逛夜市時的小點心。" },
      { type: "item", title: "板橋小籠包", text: "除了小籠包外，也有販售臭豆腐等餐點。" },
      { type: "item", title: "寶神", text: "平價小火鍋店，適合想吃熱食或與朋友聚餐時前往。" },
    ],
  },
  {
    id: 3,
    kicker: "03  /  DORM",
    title: "哇想欲歐歐睏",
    subtitle: "住宿指南｜宿舍篇",
    frontQuote: "Stay on campus.",
    frontLabel: "DORM",
    body: ["學校宿舍採四人一間配置。"],
    frontBlocks: [
      { type: "h", text: "宿舍介紹" },
      { type: "p", text: "學校宿舍採四人一間配置，每位住宿生皆有靠窗櫃、靠門大櫃、書桌上下櫃等收納空間。整體空間有限，若有大型物品需要存放，建議事先與室友協調。" },
      { type: "p", text: "宿舍費用相對親民，並包含網路、水電及冷氣費用，且距離教學區非常近，能節省大量通勤時間。早八課程時，甚至能享有「睡到最後一刻再出門」的小確幸。" },
      { type: "p", text: "宿舍夏季較容易出現蟑螂、螞蟻等小蟲問題，建議準備相關防蟲用品。住宿生活也有許多專屬回憶，例如宿舍特色活動「蘋果節」。詳細資訊請上校網查詢。" },
      { type: "h", text: "寢室設備" },
      { type: "item", text: "床位（下方為書桌，上方為床鋪）" },
      { type: "item", text: "書櫃、衣櫃、置物櫃" },
      { type: "item", text: "空調、電話、網路" },
      { type: "h", text: "公共設施" },
      { type: "item", title: "衛浴", text: "乾濕分離" },
      { type: "item", title: "交誼廳（一樓）", text: "木質地板、沙發、電視" },
      { type: "item", title: "小廚房（二、三樓）", text: "流理台、電磁爐、微波爐、電鍋、冰箱" },
      { type: "item", title: "曬衣場（四樓）", text: "需自備衣架" },
      { type: "item", title: "垃圾回收場", text: "女宿一樓後方" },
      { type: "p", text: "宿舍設有電梯，開通學生證後可刷卡使用。若遺失學生證，可至行政大樓一樓軍輔組租借電梯卡（押金 100 元），並至教務處註冊組補辦學生證。" },
    ],
    backTitle: "宿舍生活須知",
    backNote: "冷氣、熱水時段與建議攜帶用品。",
    backItems: ["冷氣時段", "熱水時段", "建議攜帶用品"],
    backBlocks: [
      { type: "h", text: "冷氣供應時間" },
      { type: "p", text: "4 月至 10 月：上午 10:00–16:00；下午 18:00–隔日 08:00。" },
      { type: "h", text: "熱水供應時間" },
      { type: "p", text: "每日 18:00–凌晨 1:00。四樓與一樓設有電熱水器，若超過供應時間，可查看其他樓層淋浴間是否仍有熱水。" },
      { type: "h", text: "建議攜帶用品" },
      { type: "item", text: "個人盥洗用品、衣物、衣架" },
      { type: "item", text: "床墊與寢具、證件（含畢業證書）、小型鎖頭" },
      { type: "item", text: "餐具、鍋具與調味料、拖鞋、雨具" },
      { type: "item", text: "耳機、延長線、簡易醫療箱、指甲剪與日常生活用品" },
    ],
  },
  {
    id: 4,
    kicker: "04  /  RENT",
    title: "哇想欲歐歐睏",
    subtitle: "住宿指南｜租屋篇",
    frontQuote: "Find a room.",
    frontLabel: "RENT",
    body: ["台藝周邊租屋價格約落在 NT$3,000–8,000。"],
    frontBlocks: [
      { type: "p", text: "台藝周邊租屋價格約落在 NT$3,000–8,000 元不等，條件較佳或設備較完整的房型也可能達萬元以上。租屋考量的不只是價格，找到適合自己的生活環境才是最重要的。" },
      { type: "h", text: "租屋區域" },
      { type: "item", title: "大觀路", text: "出校門左側，經過大觀地下道後的區域。附近有餐飲、超商，步行即可上下課。" },
      { type: "item", title: "湳雅夜市周邊", text: "跨過南橋後的區域，生活機能完整，晚上也有夜市可以覓食。" },
      { type: "item", title: "僑中一街～三街", text: "從浮洲車站出站後往右側延伸，步行約 15 分鐘內可抵達校園，適合尋找較安靜的居住環境。" },
      { type: "item", title: "龍興街", text: "便利商店密集，也有共享單車站點，距離校門口較近，鄰近市場。" },
      { type: "item", title: "府中周邊", text: "距離學校稍遠，但靠近板橋市區。若有機車或願意搭乘大眾運輸，也可以考慮。" },
      { type: "h", text: "租屋類型" },
      { type: "item", title: "雅房", text: "不包含獨立衛浴，需與其他房客共用，通常價格較便宜。" },
      { type: "item", title: "套房", text: "房間內設有獨立衛浴，生活隱私較高，價格通常也較高。" },
      { type: "item", title: "家庭式", text: "多人共同承租一間房屋或樓層，共用客廳、廚房、陽台，部分房間可能設有獨立衛浴。" },
    ],
    backTitle: "看房與簽約",
    backNote: "安全與健康永遠比價格重要。",
    backItems: ["看房注意", "簽約確認", "其他通勤選擇"],
    backBlocks: [
      { type: "h", text: "看房注意事項" },
      { type: "item", text: "可至軍輔組網站查看學校周邊租屋資訊。" },
      { type: "item", text: "不建議選擇頂樓加蓋房型，可能有安全、隔熱及漏水問題。" },
      { type: "item", text: "優先選擇有對外窗、採光良好的房間。" },
      { type: "item", text: "看房建議找家人或朋友陪同，不必不好意思多看幾次。" },
      { type: "item", title: "白天", text: "確認採光與房屋狀況" },
      { type: "item", title: "晚上", text: "觀察周邊治安與噪音" },
      { type: "item", title: "下雨天", text: "檢查是否有漏水問題" },
      { type: "h", text: "簽約前請確認" },
      { type: "item", text: "房租是否包含水電？電費計算方式（台電或房東訂價）？" },
      { type: "item", text: "網路費、瓦斯費、冷氣費如何計算？瓦斯設備位置？能否使用明火？" },
      { type: "item", text: "房間是否有對外窗、隔音、家具設備、洗衣烘衣、維修責任與共用衛浴清潔。" },
      { type: "h", text: "其他通勤選擇" },
      { type: "p", text: "若有機車或願意搭乘公車，也可考慮捷運新埔站、亞東醫院站周邊：距離較遠，但交通便利、租屋選擇較多。" },
    ],
  },
  {
    id: 5,
    kicker: "05  /  CARE",
    title: "生病去哪裡看醫生？",
    subtitle: "各種身體不適都可以在這裡找到適合的醫療資源。",
    frontQuote: "Take care.",
    frontLabel: "CARE",
    body: ["除了校外醫療院所，學校也提供固定婦產科醫師與諮商服務。"],
    frontBlocks: [
      { type: "p", text: "除了校外醫療院所外，學校也提供固定婦產科醫師與諮商服務。若有基本外傷處理、體重測量或健康相關需求，也可以至生活保健與事務組詢問。" },
      { type: "p", text: "最重要的是，無論課業或生活多忙，也請記得照顧自己的身心健康。" },
      { type: "item", title: "生活保健與事務組", text: "基本外傷、體重測量與健康諮詢" },
      { type: "item", title: "諮商服務", text: "課業與生活壓力都可以找人談談" },
      { type: "item", title: "校內婦產科", text: "固定時段看診，細節以校內公告為準" },
    ],
    backTitle: "醫療地點",
    backNote: "診所、藥局、中醫、醫院與專科推薦。",
    backItems: ["診所", "藥局", "中醫", "醫院", "專科"],
    backBlocks: [
      { type: "h", text: "診所" },
      { type: "item", title: "潘內兒科診所", text: "板橋區中正路 1 巷 18 號。公車至「林家花園」站。適合感冒、內科相關症狀。" },
      { type: "item", title: "黃何耳鼻喉科皮膚科聯合診所", text: "板橋區北門街 21 號。公車至「北門街」站。適合感冒、耳鼻喉及皮膚問題。" },
      { type: "h", text: "藥局" },
      { type: "item", title: "一誠藥局", text: "板橋區府中路 62 號。公車至「府中站」。" },
      { type: "item", title: "長春連鎖藥局－皇慶藥局", text: "板橋區南門街 81 號。公車至「府中站」。" },
      { type: "h", text: "中醫" },
      { type: "item", title: "仁心中醫", text: "板橋區北門街 42 之 3 號。公車至「北門街」站。" },
      { type: "h", text: "醫院" },
      { type: "item", title: "亞東醫院", text: "板橋區南雅南路二段 21 號。建議事先線上掛號或提前預約。" },
      { type: "item", title: "新泰醫院", text: "急診推薦院所，許多學生分享環境舒適、人潮較少、看診速度較快。急診仍建議依自身狀況選擇。" },
      { type: "h", text: "專科推薦" },
      { type: "item", title: "康宏骨科（原板橋賴骨科）", text: "板橋區四川路一段 475 號。至學校對面搭乘 234，於「豫章工商」站下車。" },
      { type: "item", title: "禧內科及林皮膚科診所", text: "板橋區府中路 112 號。可步行、騎車，或公車至「接雲寺」站。" },
      { type: "item", title: "瑞明眼科", text: "板橋區文化路一段 13 號。公車至「北門街」站。" },
      { type: "item", title: "京品牙醫診所", text: "板橋區忠孝路 97 號。掛號費約 50 元，適合日常牙科需求。" },
      { type: "item", title: "南亞復健診所", text: "許多台藝學生會前往，若有運動傷害或復健需求可考慮。" },
    ],
  },
  {
    id: 6,
    kicker: "06  /  STUDY",
    title: "圖文大一必選修課程",
    subtitle: "每年的老師分配都不太一致，以選課系統為主喔！",
    frontQuote: "First year studio.",
    frontLabel: "STUDY",
    body: ["基本設計、電腦繪圖、色彩學……"],
    frontBlocks: [
      { type: "p", text: "每年的老師分配都不太一致，以選課系統為主喔！" },
      { type: "item", title: "基本設計｜廖珮玲", text: "以設計基礎訓練為主，每年課程主題變化不大。遇到問題可參考學長姐過往作品。平時多看展覽、主動與老師討論，對作品發展與成績都有幫助。" },
      { type: "item", title: "電腦繪圖｜廖珮玲", text: "與基本設計為同一位老師，主要學習 Illustrator、Photoshop。期中、期末通常需完成圖像設計作品，建議平時累積軟體熟練度。" },
      { type: "item", title: "色彩學｜戴孟宗", text: "學習色彩基礎理論與應用，老師上課活潑有趣。期中、期末通常有報告與考試，對口頭報告有一定要求，務必聽取規範。" },
      { type: "item", title: "圖文傳播概論＆圖文科技藝術應用｜劉育君", text: "偏向理論與企劃發想。過往作業包含十大美學原理、個展企劃書等，準時出席、完成作業即可順利修課。" },
      { type: "item", title: "攝影實務｜楊炫叡", text: "從相機基礎操作開始，搭配每週主題練習。期中後進入底片攝影，期末需完成黑白底片拍攝、沖洗與放相。需要花時間，但收穫很多。" },
      { type: "item", title: "攝影學｜王志偉", text: "學習攝影基礎、底片相機構造與創作。多安排於早八，會採早鳥點名加分。期中期末需完成攝影作品，主題不限。" },
      { type: "item", title: "體育", text: "可能包含桌球、籃球、排球等。第一週教室請依學校網站公告。需穿運動服裝，準時到課、不提前離開。" },
      { type: "h", text: "大一選修" },
      { type: "item", title: "智慧財產權管理｜劉承慶", text: "透過案例或影片介紹智財概念。期中小考、期末分組報告。建議做課堂筆記。" },
      { type: "item", title: "文字造型與編排｜廖光華", text: "從文字基本架構開始學習設計方法。過往作業含名片、邀請卡、信封與海報。Illustrator 問題可向老師請教。" },
    ],
    backTitle: "畢業門檻",
    backNote: "加退選、學分與畢業前必做事項。細節以當年度系辦公告為準。",
    backItems: ["加退選", "學分", "畢業展與實習"],
    backBlocks: [
      { type: "h", text: "加退選提醒" },
      { type: "p", text: "請留意課程加退選時間（含校際選課）：09/07 14:00 ～ 09/21 21:00。期間請確認本學期學分是否符合最低修課標準、想修的課是否額滿、是否與必修衝堂。" },
      { type: "h", text: "畢業學分" },
      { type: "p", text: "畢業總學分：128 學分。畢業前須完成學分要求、撰寫與發表符合規定的學士論文、參與校內外畢業展，以及英文畢業門檻或同等語言檢定。" },
      { type: "item", title: "專業科目｜85 學分", text: "專業必修 51、專業選修 34。" },
      { type: "item", title: "通識課程｜26 學分", text: "共同語文 6、人文科學 6、自然科技 4、社會科學 6、跨領域整合 4。" },
      { type: "item", title: "體育課程｜6 學分", text: "必修 2、選修 4。" },
      { type: "item", title: "院課程", text: "傳院選修 2 學分。" },
      { type: "item", title: "跨域選修｜4 學分", text: "跨校、跨院、跨系課程皆可列入。" },
      { type: "item", title: "校內專業實習", text: "0 學分，上下學期須依規定完成事項。" },
      { type: "p", text: "學分規定可能因年度調整。以上依 115 學年度學分表整理，每學期開課前請再確認系上最新規劃與系辦公告，避免畢業前才發現學分不足。" },
    ],
  },
  {
    id: 7,
    kicker: "07  /  EVENTS",
    title: "系學會活動預告",
    subtitle: "等你來參加。確切日期以當學期公告為準。",
    frontQuote: "Save the dates.",
    frontLabel: "EVENTS",
    body: ["新生茶會、期初大會、迎新……"],
    frontBlocks: [
      { type: "item", title: "新生茶會", text: "開學前後的第一場見面。名字、科系、一句近況就夠。填表後會有小禮。" },
      { type: "item", title: "期初大會", text: "認識系學會幹部、聽本學期行事，也是提問的好時機。" },
      { type: "item", title: "迎新", text: "給新生的大型活動，讓你快速認識同學與學長姐。" },
      { type: "item", title: "手作交流工作坊", text: "用一天把紙、印、裝訂或小物做起來，適合想動手的人。" },
      { type: "item", title: "萬聖節", text: "變裝、拍照、小小熱鬧一下。" },
    ],
    backTitle: "下半學期也有你",
    backNote: "系羽、講座、聖誕、攝影展、系展與系烤。",
    backItems: ["系羽", "講座", "聖誕節", "攝影交流展", "系展", "系烤"],
    backBlocks: [
      { type: "item", title: "系羽", text: "系上羽球聚。初學也能上場，重點是流汗與認識人。" },
      { type: "item", title: "外聘講師講座", text: "業界與學長姐回娘家，聽一場可能就決定你下一個專題方向。" },
      { type: "item", title: "聖誕節", text: "交換小物、布置與期末前的換氣時間。" },
      { type: "item", title: "攝影交流展", text: "把作業與私心創作拿出來並置，看別人怎麼看世界。" },
      { type: "item", title: "系展", text: "圖文一年一度的集體亮相，布展本身也是課程。" },
      { type: "item", title: "系烤", text: "學期尾聲的火與食物。記得登記與飲食習慣。" },
    ],
  },
  {
    id: 8,
    kicker: "08  /  VOLLEY",
    title: "圖文系排",
    subtitle: "圖文系排需要你！初學也歡迎。",
    frontQuote: "Pass it on.",
    frontLabel: "VOLLEY",
    body: ["從接球、舉球、攻擊開始。"],
    frontBlocks: [
      { type: "h", text: "訓練內容" },
      { type: "p", text: "剛加入系排時，會從排球基礎開始：接球、舉球、攻擊、隊形與跑位。除了基本技巧，也會加入小遊戲提升反應與團隊默契，並搭配體能訓練。" },
      { type: "p", text: "運動傷害防護是訓練的一環，每次練習皆從熱身開始。若發生狀況，隊員會協助即時處理，以安全為優先。" },
      { type: "h", text: "球隊活動" },
      { type: "p", text: "每學期學校皆會舉辦新生盃與校長盃；系排也會參與全美盃、傳廣盃等校外賽事，並不定期與其他學校友誼賽。畢業季有較輕鬆的「送舊盃」。平時也歡迎自行揪團打球。" },
    ],
    backTitle: "目前球隊狀況",
    backNote: "男排與女排的集合方式不同，歡迎來問。",
    backItems: ["男排", "女排", "練習時間"],
    backBlocks: [
      { type: "h", text: "男排" },
      { type: "p", text: "因目前隊員人數較少，隊伍安排可能有所調整，後續將以隊員討論與投票結果為主。希望大家盡量配合練習時間到場；練習結束後會安排檢討、收操或加強訓練，結束時間可能較晚。通勤同學可依交通時間彈性離開。" },
      { type: "h", text: "女排" },
      { type: "p", text: "目前圖文女排因人數不足，暫與美術系排球隊合併訓練。未來若人數充足，有機會重新獨立成隊。" },
      { type: "item", title: "練習時間", text: "每週兩次，18:30–22:00" },
      { type: "item", title: "練習地點", text: "台藝排球場（室外）" },
      { type: "p", text: "歡迎喜歡排球的學妹加入。即使是初學也不用害怕，許多學姊也是從零開始。也歡迎其他年級、突然想打球的朋友加入球局。" },
      { type: "p", text: "圖文系排需要你！圖文系排需要你！圖文系排需要你！" },
    ],
  },
  {
    id: 9,
    kicker: "09  /  FAQ",
    title: "常見問題",
    subtitle: "筆電、繪圖板、畫具與相機，不必一次買齊。",
    frontQuote: "Do I need a laptop?",
    frontLabel: "FAQ",
    body: ["建議準備一台筆電。"],
    frontBlocks: [
      { type: "h", text: "需要購買筆電嗎？" },
      { type: "p", text: "建議準備一台筆電。系上課程多會使用電腦進行設計軟體與作品製作，通識報告也可能需要。Windows 與 Mac 皆可。常用軟體包含 Adobe Illustrator、InDesign、Photoshop。選購時建議優先考量運算效能、記憶體與螢幕顯色。暫時沒有筆電也不用擔心，圖書館與教學研究大樓皆有公用電腦。" },
      { type: "h", text: "需要購買繪圖板與平板嗎？" },
      { type: "p", text: "兩者皆非課程必需品。繪圖板依個人創作方式決定；平板可用於筆記、閱讀與部分作業，能提升便利性。" },
      { type: "h", text: "需要準備畫具嗎？" },
      { type: "p", text: "不需要一次購買大量畫具。少部分課程如選修素描，會需要素描本、素描鉛筆、軟橡皮等。缺少的美術用品也可至學校後街附近的美術用品社購買。" },
      { type: "h", text: "需要購買相機嗎？" },
      { type: "p", text: "系上部分課程會使用數位相機與底片相機。大一攝影課程依慣例每週拍攝作品，選購需求可找老師或學長姐討論。攝影實務會需要 35mm 底片相機與底片。大二通過系上商業攝影相關資格後，可依規定租借系上 Canon 5D3，詳洽系辦助教。" },
    ],
    backTitle: "其他聯絡資訊",
    backNote: "地址、電話、系辦時間與系學會。",
    backItems: ["地址", "電話", "系辦時間", "系學會"],
    backBlocks: [
      { type: "item", title: "地址", text: "220 新北市板橋區大觀路一段 59 號" },
      { type: "item", title: "校本部電話", text: "02-2272-2181" },
      { type: "item", title: "校安專線", text: "02-2967-4948" },
      { type: "item", title: "圖文系辦分機", text: "#2251、#2252、#2253" },
      { type: "item", title: "圖文系信箱", text: "gca@gmail.com" },
      { type: "h", text: "圖文系辦洽公時間" },
      { type: "item", title: "寒暑假", text: "週一至週四 09:00–17:00（週五至週日休息）" },
      { type: "item", title: "學期間", text: "週一至週五 09:00–17:00；週六 09:00–17:00（週日休息）" },
      { type: "item", title: "午休", text: "12:00–13:30" },
      { type: "h", text: "系學會" },
      { type: "item", title: "會長　國語者", text: "0971-798-371　rogerkuo1222@gmail.com" },
      { type: "item", title: "副會長　黃楚茵", text: "0909-733-906　chuuyinooz@gmail.com" },
    ],
  },
];

export const TEA_PARTY = {
  kicker: "SPECIAL  /  TEA",
  volume: "X",
  title: "新生茶會",
  subtitle: "歡迎各位新生加入台藝圖文的大家庭。",
  lead: "這不是第九張卡片的延續，而是一場獨立的邀請。",
  body: [
    "歡迎各位新生加入台藝圖文的大家庭。為了讓大家更快融入圖文系的環境、熟悉系上生活，也認識未來一起學習、創作的夥伴，我們準備了這場茶會。",
    "透過輕鬆有趣的交流與互動，讓新生彼此認識，也和老師、學長姐聊聊系上的課程、活動與生活點滴。不必準備完整的自我介紹，名字、一句近況，就已經足夠。",
    "現場會有人帶路、聽你還沒想好的問題，也會把系上日常慢慢說給你聽。願意的話，先填寫調查表單，讓我們知道你的飲食與時間。",
  ],
  prompt: "新生茶會調查表單！精美小禮等著你，期待與你相見...",
};

export const TABS = [
  { id: "pack", en: "GUIDE", zh: "新生指南" },
  { id: "qr", en: "LINKS", zh: "常用連結" },
  { id: "about", en: "ABOUT", zh: "關於我們" },
];

export const QR_ITEMS = [
  { key: "class", title: "圖文115班群", caption: "班級群組", file: "/assets/qr/01 圖文115 班群.png", url: LINKS.lineClass },
  { key: "ntua", title: "台藝人請進", caption: "臉書社團", file: "/assets/qr/02 台藝人請盡.png", url: LINKS.facebook },
  { key: "ig", title: "系學會 IG", caption: "Instagram", file: "/assets/qr/03系學會 IG.png", url: LINKS.instagram },
  { key: "community", title: "圖文社群", caption: "系級專屬交流社群", file: "/assets/qr/04 圖文社群.png", url: LINKS.lineCommunity },
  { key: "courses", title: "台藝好課", caption: "課程文件", file: "/assets/qr/05 台藝好課.png", url: LINKS.courses },
];
